# Generated by Django 5.2.5 on 2025-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterbooking',
            name='contact',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelterbooking',
            name='owner_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelterbooking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
