# Generated by Django 5.2.5 on 2025-10-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_shelterbooking_contact_shelterbooking_owner_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelterbooking',
            old_name='check_in_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='shelterbooking',
            old_name='check_out_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='groomingbooking',
            name='adopter',
        ),
        migrations.RemoveField(
            model_name='groomingbooking',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='groomingbooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shelterbooking',
            name='adopter',
        ),
        migrations.RemoveField(
            model_name='shelterbooking',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='shelterbooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shelterbooking',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='vaccinationbooking',
            name='adopter',
        ),
        migrations.RemoveField(
            model_name='vaccinationbooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vaccinationbooking',
            name='vaccination_time',
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='owner_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelterbooking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelterbooking',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelterbooking',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccinationbooking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationbooking',
            name='owner_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationbooking',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groomingbooking',
            name='grooming_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groomingbooking',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groomingbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='shelterbooking',
            name='owner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shelterbooking',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shelterbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='vaccinationbooking',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccinationbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='vaccinationbooking',
            name='vaccine_type',
            field=models.CharField(max_length=100),
        ),
    ]
