# Generated by Django 5.2.5 on 2025-10-24 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_check_in_date_shelterbooking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterbooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shelter_bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
