# Generated by Django 5.2.5 on 2025-10-24 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_shelterbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationbooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccinationbooking',
            name='special_notes',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
