# Generated by Django 5.2.5 on 2025-10-24 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_vaccinationbooking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groomingbooking',
            name='grooming_type',
        ),
        migrations.RemoveField(
            model_name='groomingbooking',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='special_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grooming_bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
