# Generated by Django 5.2.5 on 2025-10-29 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_groomingbooking_grooming_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groomingbooking',
            options={'ordering': ['-appointment_date'], 'verbose_name': 'Grooming Booking', 'verbose_name_plural': 'Grooming Bookings'},
        ),
        migrations.AlterModelOptions(
            name='shelterbooking',
            options={'ordering': ['-start_date'], 'verbose_name': 'Shelter Booking', 'verbose_name_plural': 'Shelter Bookings'},
        ),
        migrations.AlterModelOptions(
            name='vaccinationbooking',
            options={'ordering': ['-vaccination_date'], 'verbose_name': 'Vaccination Booking', 'verbose_name_plural': 'Vaccination Bookings'},
        ),
        migrations.RemoveField(
            model_name='groomingbooking',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='shelterbooking',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='vaccinationbooking',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='pet_owner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='selected_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grooming_bookings_as_selected_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelterbooking',
            name='pet_owner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shelterbooking',
            name='selected_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter_bookings_as_selected_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationbooking',
            name='pet_owner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationbooking',
            name='selected_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_bookings_as_selected_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
