# Generated by Django 5.2.5 on 2025-11-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_groomingbooking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groomingbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shelterbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vaccinationbooking',
            name='email',
        ),
    ]
